### ISSUE TITLE
Fix compilation on Solaris

### ISSUE THREAD

**Issue by clente** [curso-r/stockfish#10]
Error persists on CRAN (even though GCC has been added as system requirement):

```
"bitboard.h", line 371: Error: #error "Compiler not supported.".
```

Cannot reproduce with `rhub::check_on_solaris()`.

**Comment by gaborcsardi** [comment]
Did you submit it to CRAN again? Or this is from R-hub?

**Comment by clente** [comment]
I submitted it to CRAN again on the 4th. I cannot reproduce this error on R-hub.

**Comment by gaborcsardi** [comment]
How do you know that CRAN tested it on Solaris again? Did they tell you in private?

**Comment by clente** [comment]
They've sent me an email and I think it's safe to say they are talking about Solaris. v1.0's error was [on Solaris](https://cran-archive.r-project.org/web/checks/2020/2020-12-19_check_results_stockfish.html) and, in their most recent email to me, they said:

```
Thanks, we still see:

"bitboard.h", line 371: Error: #error "Compiler not supported.".
```

Since they **still see** the same error, I'm assuming it's Solaris. Of course I cannot be sure because `{stockfish}` passes on all R-hub checks.

**Comment by gaborcsardi** [comment]
Can you try to reply and ask if this is on Solaris, and if yes, then tell them that it needs gcc?

**Comment by clente** [comment]
I did, but I'm still waiting for a reply. This is what I asked (redacted for privacy reasons):

```
Thanks for the feedback, X.

Not sure if I can ask you for help, so I'm sorry if I'm being inconvenient.

Is there a way for me to require GCC to be used as the compiler on Solaris? These are my SystemRequirements: C++11, GCC, clang or ICC. I cannot reproduce the error you see with rhub::check_on_solaris().
```

**Comment by gaborcsardi** [comment]
OK, then let's wait a bit for the reply. I _think_ there is a trick to force GCC, you need to specify `LinkingTo: Rcpp`. Not the most elegant, but we can do that in the worst case.

**Comment by clente** [comment]
I still haven't heard back from them. Maybe I'll just try to fix the package and resubmit.

@gaborcsardi, just adding `LinkingTo: Rcpp` will require GCC?

**Comment by gaborcsardi** [comment]
> @gaborcsardi, just adding LinkingTo: Rcpp will require GCC?

Yes, AFAICT Brian Ripley's Solaris script automatically switches to GCC when you use Rcpp, because Rcpp does not work with the Solaris compilers.

**Comment by gaborcsardi** [comment]
You might need to actually use something from Rcpp, otherwise you'll get another check error.

**Comment by clente** [comment]
Submitted again after linking to `{Rcpp}`.

In the meantime, I was looking at other packages and saw that `{lubridate}` has this on its `SystemRequirements`: "a recent-enough C++11 compiler (such as g++-4.8 or later)". Maybe that could work?

**Comment by gaborcsardi** [comment]
> In the meantime, I was looking at other packages and saw that {lubridate} has this on its SystemRequirements: "a recent-enough C++11 compiler (such as g++-4.8 or later)". Maybe that could work?

It might, but it would require special handling from CRAN, I am pretty sure that it is not automatic.

**Comment by clente** [comment]
Maybe changing the error message could work? It's very frustrating not to be able to reproduce the error.

```
Thanks, we still see the unhelpful and unresolved error message:

"bitboard.h", line 371: Error: #error "Compiler not supported.".
*** Error code 2
make: Fatal error: Command failed for target `benchmark.o'
ERROR: compilation failed for package ‘stockfish’

with no configure check and no attempt to find a suitable compiler.
```

**Comment by gaborcsardi** [comment]
This is very frustrating indeed. 

So the package does not depend on Rcpp now, right?

**Comment by clente** [comment]
I removed the dependency for now, but I could revert the commit.

Is it in bad taste to explain the necessity of GCC in `cran-comments`? Or even ask more details about the error since they still haven't replied to my email?

**Comment by gaborcsardi** [comment]
It is fine, but IDK if they would reply to that. So I would just submit a "fixed" version of the package.

Maybe we could then give a better error message, e.g. add another header file, which is compiled first, and fail early with a nice error message?

Or go with the Rcpp fix?

**Comment by clente** [comment]
What's the Rcpp fix? Adding `LinkingTo: Rcpp` was my last attempt (submitted 6 days ago).

**Comment by gaborcsardi** [comment]
Yes, it is that. Did you get a reply to that at all?

**Comment by gaborcsardi** [comment]
Or the last reply was to that I assume?

**Comment by clente** [comment]
The last reply was to that.

**Comment by gaborcsardi** [comment]
Yeah, I guess they checked the package manually, and the compiler selection of their automated testing did not apply there.

Shall we try to give a better error message then? Btw. you can probably reproduce the error on R-hub with:

```r
rhub::check(platform = "solaris-x86-patched-ods")
```

you'll get this:
https://artifacts.r-hub.io/stockfish_0.1.0.9000.tar.gz-da3b427f4f0547629dc2ac1dc4406348/stockfish.Rcheck/00install.out

```
/opt/developerstudio12.6/bin/CC -std=c++11 -library=stdcpp,CrunG3  -I"/opt/R/R-4.0.3/lib/R/include" -DNDEBUG   -I/opt/csw/include   -KPIC  -O -xlibmil -xtarget=native -xcache=generic -nofstore  -c benchmark.cpp -o benchmark.o
"bitboard.h", line 371: Error: #error "Compiler not supported! Must be either GCC or MSVC compatible.".
gmake: *** [/opt/R/R-4.0.3/lib/R/etc/Makeconf:181: benchmark.o] Error 2
```

I am not sure how to make this better, though, it clearly tells you that you need GCC.

**Comment by clente** [comment]
Omg, thanks for that command. I used `rhub::check_on_solaris()`, but it wasn't raising the error!

The error message you see is new, added in 0acc48bc7d800400fe3746540eae6129167b0b7f. I haven't resubmitted the package with this fix yet, do you think I should?

**Comment by gaborcsardi** [comment]
Yeah, you could make it even more explicit, e.g. something along the lines of 

```
The Stockfish chess engine only works with GCC and MSVC compatible compilers and this R package only
works with GCC or clang. Solaris and Oracle compilers will not work, sorry. 
```

**Comment by clente** [comment]
I changed the error message as discussed above and received the following feedback:

```
Thanks, we see:

   Found the following (possibly) invalid URLs:
     URL: https://www.tidyverse.org/lifecycle/#maturing (moved to
https://lifecycle.r-lib.org/articles/stages.html)
       From: README.md
       Status: 200
       Message: OK

Please change http --> https, add trailing slashes, or follow moved
content as appropriate.

Please fix and resubmit.
```

I thought the problem was solved, fixed the URL issue, and resubmitted the package. But today I got this message from the same reviewer:

```
Thanks, apparently you install a binary, hence this is not platform
independent code that we ask for. FOr examples, it does not even install
on Solaris.

Also, please give your full name in the maintaier field.

Please fix and resubmit.
```

Not sure what to do. Fixing the package seems pretty pointless since it might never get to be "platform independent". I felt compelled to [tweet about it](https://twitter.com/clente_/status/1356579681252872193?s=20)... Maybe someone on Twitter can help with this kind of issue.

**Comment by clente** [comment]
Solved in https://github.com/curso-r/stockfish/pull/11
