### ISSUE TITLE
R6 class finalizer

### ISSUE THREAD

**Issue by dfalbel** [curso-r/stockfish#2]
You could have a R6 class [finalizer](https://r6.r-lib.org/articles/Introduction.html#finalizers-1) in order to fix: 

> Don’t forget to assign: if you simply run fish$new() without assigning it to an object, you will have to either restart the session or kill the Stockfish process manually in order not to have dangling engines eating up your RAM.

**Comment by clente** [comment]
That is a great idea. Thanks for pointing it out!
